
# default recipe to display help information
help:
  @echo "Run 'west init' and 'west update' to setup dependencies"
  @just --list

alias b := build

build:
    west build -b nrf52840dk/nrf52840

alias f := flash

flash: build
    west flash


