
# default recipe to display help information
help:
  @echo "Run 'west init' and 'west update' to setup dependencies"
  @just --list

alias b := build

build:
    west build --pristine -b nrf52840dk/nrf52840 
    # -- -DDTC_OVERLAY_FILE=default.overlay

alias f := flash

flash: build
    west flash --runner jlink


